server.port = 8585
server.servlet.context-path = /workintech

#Actuator
management.endpoints.web.exposure.include = info,health,mappings
info.app.name=Developer Management Application
info.app.description=Spring Boot Dependency Injection and CRUD Project
info.app.version=1.0.0

management.info.env.enabled=true
